import type { Metadata } from 'next';
import { Instrument_Serif, Oswald, Xanh_Mono } from 'next/font/google';
import '@/styles/globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/provider/ThemeProvider';
import { TooltipProvider } from '@/components/ui/tooltip';
import AuthWrapper from '@/features/auth/components/AuthWrapper';

const owswald = Oswald({
  variable: '--font-sans',
  subsets: ['latin'],
});

const instrumentSerif = Instrument_Serif({
  variable: '--font-serif',
  subsets: ['latin'],
  weight: ['400'],
});
const xanhMono = Xanh_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        owswald.variable,
        instrumentSerif.variable,
        xanhMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <AuthWrapper>
            <TooltipProvider>
              {children}
              <Toaster />
            </TooltipProvider>
          </AuthWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
